services:
  db:
    image: mongo
    container_name: ${SLUG}-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ROOT_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${ROOT_DB_PASS}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - ./scripts/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./db/:/data/db
    networks:
      - net
      - priv

  mongo-express:
    image: mongo-express
    container_name: ${SLUG}-db-admin
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin 
      ME_CONFIG_BASICAUTH_PASSWORD : pass
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ROOT_DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ROOT_DB_PASS}
      ME_CONFIG_MONGODB_URL: mongodb://${ROOT_DB_USER}:${ROOT_DB_PASS}@${SLUG}-db:27017/
    networks:
      - priv
  
networks:
  net:
    name: ${SLUG}-publ
    driver: bridge
  priv:
    name: ${SLUG}-priv
    driver: bridge
